import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Blog from './Components/Blog';
import Hero from './Components/Hero';
import Point from './Components/Point';
import Question from './Components/Question';
import Shiping from './Components/Shiping';
import Footer from './Components/Footer';


export default function Home() {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Industry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
        
      </Head>
      

       <Hero
       heading='New marketplace that allows you to buy in bulk'
       text="Hypeindustry is a one-of-a-kind Platform+Marketplace offering Bulk
       Wholesale goods from Stores, Boutiques,Wholesalers & Resellers for the  
       Footwear  Apparel & Accessory industry"
       />
       <Blog/>
       <Question/>
       <Point/>
       <Shiping/>
       <Footer/>


   
    </div>
    
    </>
  )
}
